### ISSUE TITLE
Support custom backup/restore locations

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/remote-controller#147]
With https://github.com/uselagoon/lagoon/pull/2820 now merged in, Lagoon now supports custom backup and restore locations natively. Once the remote-controller has support for accepting and passing these variables, we'll have the ability to setup custom backup/restore locations on a per-cluster basis.

**Comment by shreddedbacon** [comment]
If these values only get passed in via build pods, remote-controller can support passing in any `LAGOON_FEATURE_FLAG_DEFAULT|FORCE` prefixed variables directly into build pods. The logic of remote-controller has no need to understand what these variables are or what they do, only that they exist.

We should update the build script to leverage these instead, this makes it obvious when the controller is providing a value then.

**Comment by shreddedbacon** [comment]
Closing in favor of https://github.com/uselagoon/build-deploy-tool/issues/55 (and there may be one that makes it into `uselagoon/lagoon` if needed)
