### ISSUE TITLE
Routes links doubled in message after build

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/remote-controller#47]
# Describe the bug

The route(s)' links in the message after a build, are doubled.

## To Reproduce

Check if in the configmap you have both `LAGOON_ROUTE` and `LAGOON_ROUTES` with value and run a build

## Expected behavior

Just a single link per route

Check https://github.com/amazeeio/lagoon-kbd/pull/42/files

**Comment by shreddedbacon** [comment]
I think this is because `LAGOON_ROUTES` contains all the routes, including `LAGOON_ROUTE`. So need to do some check that only uses one or the other, should be fairly easy.

**Comment by shreddedbacon** [comment]
Closing, as I believe this has been resolved on the Lagoon-core side in logs2notifications
